### PR TITLE
Charlottelaw/jdi 14 tab navigation

### PR DESCRIPTION
**Pull request by CharlotteLaw**
### Description
Tab Navigation Temp

### Screenshots
[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy! Use the provided image template. Drag the desired image into the PR, then copy the link into the placeholder."
N/A

## How to review
Review the new `stack` and `screens` folder under Navigation. I also made a new BottomTabNavigator, MainNavigator, and types.

## Next steps
Connect all the screens with this tab navigator. 

## Relevant links
N/A

### Related PRs
[//]: # "Add related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @philipye314

### CODE REVIEW

**Comment by CharlotteLaw** [comment]
Updated!

**Review by philipye314 — CHANGES_REQUESTED** [review]
The main thing that needs to be fixed right now is you should pull from `main` and fix all merge conflicts. This will help you see the current state of the app and how things should work along with your navigation, so you won't have to work with weird, dummy screens anymore!

**Review by philipye314 — APPROVED** [review]
fixed it for you :)

**Comment by CharlotteLaw** [comment]
Thank you so much!!!

**Pull request merged**
